name: "new post"
description: "new post"
title: "new post"
labels: ["post"]
body:
- type: input
  id: "article_title"
  attributes:
    label: "Article title"
    placeholder: "new post"
    description: "Article title"
- type: "dropdown"
  id: "article_kind"
  attributes:
    label: "Article kind"
    multiple: false
    description: "article, poem"
    options:
      - article
      - poem
  validations:
    required: true
- type: "textarea"
  id: "article_content"
  attributes:
    label: "Article content"
    placeholder: "Hello, world!"
    description: "Article content"
  validations:
    required: true
